engines:
             eslint:
               enabled: true
             nodesecurity:
               enabled: true
             fixme:
               enabled: true
             duplication:
               enabled: true
               config:
                 languages:
                   - javascript
           ratings:
             paths:
               src/**
               tasks/**
               test/**